project:
  type: website

website:
  title: "Ashlynn Lu"
  bread-crumbs: true
  back-to-top-navigation: true
  repo-url: https://github.com/AshlynnLu/profile-page
  repo-actions: [edit, issue]
  
  navbar:
    left:
      - text: "Writing"
        file: writing.qmd
      - text: "Photo"
        file: photo.qmd
      - text: "About"
        file: about.qmd
    right:
      - icon: github
        href: https://github.com/AshlynnLu
      - icon: linkedin
        href: https://www.linkedin.com/in/kexin-lu-246256228
      - icon: facebook
        href: https://www.facebook.com/kexin.lu.370
      - text: " "
      
  page-footer:
      background: light
      border: true
      left: "© Ashlynn Lu 2024"
      center: ""
      right:
        - icon: github
          href: https://github.com/AshlynnLu
        - icon: linkedin
          href: https://www.linkedin.com/in/kexin-lu-246256228
        - icon: facebook
          href: https://www.facebook.com/kexin.lu.370
format:
  html:
    theme: sandstone
    css: styles.css



