<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.542">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ashlynn Lu">
<meta name="dcterms.date" content="2022-08-19">

<title>Ashlynn Lu - Investigating the impact of age and sex on guillemot survival</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Ashlynn Lu</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../research.html"> 
<span class="menu-text">Writing</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../photo.html"> 
<span class="menu-text">Photo</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/AshlynnLu"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/kexin-lu-246256228"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.facebook.com/kexin.lu.370"> <i class="bi bi-facebook" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="dropdown-header">
 <span class="menu-text"> </span></li>
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Investigating the impact of age and sex on guillemot survival</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">analysis</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Ashlynn Lu </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">August 19, 2022</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#constant-model" id="toc-constant-model" class="nav-link active" data-scroll-target="#constant-model">1. Constant Model</a></li>
  <li><a href="#sex-dependent-survival-probabilities" id="toc-sex-dependent-survival-probabilities" class="nav-link" data-scroll-target="#sex-dependent-survival-probabilities">2. Sex dependent survival probabilities</a></li>
  <li><a href="#model-with-age-dependent-survival-probabilities" id="toc-model-with-age-dependent-survival-probabilities" class="nav-link" data-scroll-target="#model-with-age-dependent-survival-probabilities">3. Model with Age-dependent survival probabilities</a></li>
  <li><a href="#models-with-survival-probabilities-age-and-sex-dependent" id="toc-models-with-survival-probabilities-age-and-sex-dependent" class="nav-link" data-scroll-target="#models-with-survival-probabilities-age-and-sex-dependent">4. Models with survival probabilities age and sex dependent</a></li>
  <li><a href="#model-selection" id="toc-model-selection" class="nav-link" data-scroll-target="#model-selection">Model selection</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  <li><a href="#reference" id="toc-reference" class="nav-link" data-scroll-target="#reference">Reference</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/AshlynnLu/profile-page/edit/main/posts/2022-08-19_guillemot-survival/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/AshlynnLu/profile-page/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>The project is motivated by a capture-recapture dataset from the largest colony of common guillemot in the Baltic Sea, Stora Karlsö. Data were recorded from 2009 to 2021.</p>
<p>Photo by Aron Heidström, <a href="http://www.balticseabird.com/auklab/"> Baltic Seabird Project</a></p>
<p><img src="images/lab.jpg" class="img-fluid"></p>
<p>Seabirds inhabit marine ecosystems and they share several life history traits: high adult survival, a progressive access to reproduction at relatively old ages, a low reproductive rate and a low number of natural predators. Adult survival as well as juvenile survival, are considered important traits that influence population dynamics in seabird species. However, survival estimation can be challenging.</p>
<p>Ideally, individuals would be followed from birth to death with a given study period, but this is rarely possible for wild populations. The problem arises since the observation process relating to individuals is imperfect, and hence we cannot always make a direct measurement of the state variable of interest (i.e.&nbsp;alive or dead). In the wild, if an individual is not observed two options are possible: (i) it is dead, or (ii) it is still alive (but it has not been observed). This problem can be addressed using the capture-mark-recapture (CMR) method.</p>
<p>CMR methods use data collection protocols where observers go into the field at a series of capture events, denoted t = 1, . . . , T. At each capture event, the observer marks the new individuals, records all observed individuals (already marked) and releases them back into the population. This leads to data corresponding to the capture history of each individual, detailing at which capture occasions they are observed or not.</p>
<p>A capture history or capture-recapture takes the form of a vector of length the number of encounter occasions <span class="math inline">\(T\)</span>, and records the value 1 for a live encounter and 0 when an individual was not encountered. This data set also contains the sex of each individual as an additional information. The main interest in this project is to estimate the main parameters, which are the recapture and the apparent survival probabilities. The survival probabilities, denoted by <span class="math inline">\(\phi_t\)</span>, represent the probability of that an individual is alive at time <span class="math inline">\(t\)</span> and survives until time <span class="math inline">\(t+1\)</span> (for time <span class="math inline">\(t = 1, ..., T-1\)</span>, for all individuals). Similarly, the recapture probabilities, denoted by <span class="math inline">\(p_t\)</span> represent the probability of observing an individual at time <span class="math inline">\(t\)</span> (from <span class="math inline">\(t = 2, ..., T\)</span> and for all individuals).</p>
<p>We use <span class="math inline">\(p_t\)</span> to denote the recapture probability at occasion <span class="math inline">\(t\)</span>, ang <span class="math inline">\(\phi_t\)</span> to denote the apparent survival probability between occasion <span class="math inline">\(t\)</span> and <span class="math inline">\(t+1\)</span>.</p>
<p>The primary interest in these studies is usually the estimation of survival probabilities and the associated factors (or covariates) that may influence these. Such covariates may include for example, age, environmental covariates, sex, individual heterogeneity, etc. In this project we will focus on the estimation of age and/or sex-dependent survival probabilities for this colony of common guillemots. This will involve developing statistical models to incorporate and assess the impact of age and sex on the survival estimates within a formal modelling framework in order to improve our understanding of the population which in turn may aid in their management and conservation.</p>
<p>In the next table, and for simplicity, we present a subset of the data,</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">2009</th>
<th style="text-align: right;">2010</th>
<th style="text-align: right;">2011</th>
<th style="text-align: right;">2012</th>
<th style="text-align: right;">2013</th>
<th style="text-align: right;">2014</th>
<th style="text-align: right;">2015</th>
<th style="text-align: right;">2016</th>
<th style="text-align: right;">2017</th>
<th style="text-align: right;">2018</th>
<th style="text-align: right;">2019</th>
<th style="text-align: right;">2020</th>
<th style="text-align: right;">2021</th>
<th style="text-align: left;">Sex</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">M</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">F</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">F</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">F</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">F</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">F</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Each row contains a capture history across 13 occasions for each individuals with the last column indicate their sex. The database contains information about 117 individuals, all of them ringed as chicks i.e.&nbsp;at age 1, therefore <span class="math inline">\(T = 13\)</span>.</p>
<p>In this study we will use the standard Cormack-Jolly-Seber (CJS) model which is considered a general framework for several number of extensions and which is conditional at initial capture (ringing time). More information about these and related models see: Serber and Schofield, 2019; McCrea and Morgan, 2015; king et al.&nbsp;2010 (among many others).</p>
<p>We are going to implement CJS models in the frequentist approach, building likelihood function for each model, then use <code>optim</code> function to find the maximum likelihood estimate (MLE) for <span class="math inline">\(\boldsymbol{p}\)</span> and <span class="math inline">\(\boldsymbol{\phi}\)</span> parameters.</p>
<section id="constant-model" class="level2">
<h2 class="anchored" data-anchor-id="constant-model">1. Constant Model</h2>
<p>We start with the most basic model: model with constant <span class="math inline">\(\boldsymbol{p}\)</span> and <span class="math inline">\(\boldsymbol{\phi}\)</span> parameters. In other words, recapture and survival probabilities are invariant with age, time and sex.</p>
<p>Firstly, we need to transform the capture history into m-array format. M-array is a <span class="math inline">\((T-1) \times T\)</span> matrix with each row representing a released occasion (<span class="math inline">\(i = 1, ..., T-1\)</span>), and each column representing a recapture occasion (<span class="math inline">\(j = 2, ..., T\)</span>). The last column contains the number of individuals that have never been recaptured in each released occasion. For example, the <span class="math inline">\([1, 2]\)</span> cell contains the number of individuals which released in occasion 1 and next recaptured in occasion 2.</p>
<p>We have defined a function <code>marray</code> in <code>functions.R</code> file to help us to transform the data. Let <code>marr.full</code> be the m-array of the full data set, which is shown below.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">j = 2</th>
<th style="text-align: right;">j = 3</th>
<th style="text-align: right;">j = 4</th>
<th style="text-align: right;">j = 5</th>
<th style="text-align: right;">j = 6</th>
<th style="text-align: right;">j = 7</th>
<th style="text-align: right;">j = 8</th>
<th style="text-align: right;">j = 9</th>
<th style="text-align: right;">j = 10</th>
<th style="text-align: right;">j = 11</th>
<th style="text-align: right;">j = 12</th>
<th style="text-align: right;">j = 13</th>
<th style="text-align: right;">never recaptured</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">i = 1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">i = 2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">i = 3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">i = 4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">i = 5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">i = 6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">i = 7</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">i = 8</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">i = 9</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">i = 10</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">17</td>
</tr>
<tr class="odd">
<td style="text-align: left;">i = 11</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">26</td>
</tr>
<tr class="even">
<td style="text-align: left;">i = 12</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">6</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Next we are going to form a likelihood function for the constant model.</p>
<p>Let <span class="math inline">\(\underline{x}\)</span> be the capture history of the whole data where <span class="math inline">\(x_i\)</span> is the capture history of individual <span class="math inline">\(i = 1, ..., 117\)</span>, and <span class="math inline">\(\boldsymbol{\theta}\)</span> be the parameters used to estimate <span class="math inline">\(p\)</span> and <span class="math inline">\(\phi\)</span>. Since we are going to use <code>optim</code> to maximise the negative log likelihood function to give the MLE of the desired parameters, we need to remove the boundary of the parameters. Let <span class="math inline">\(\boldsymbol{\theta}\)</span> be an array contains the logit transformation of the parameters <span class="math inline">\(\phi\)</span> and <span class="math inline">\(p\)</span>, then the boundary of <span class="math inline">\(\boldsymbol{\theta}\)</span> is now all real numbers instead of <span class="math inline">\((0, 1)\)</span>.</p>
<p>Each row of the m-array follows a multinomial distribution with parameters <span class="math inline">\(N_i\)</span> and <span class="math inline">\(\underline{q}\)</span>, then the likelihood function of the whole data is the product of multinomial distribution, i.e.</p>
<p><span class="math display">\[
L(\underline{x};\theta) = \prod_{i}^{T-1}Multinomial(N_i, \underline{q})
\]</span> where <span class="math inline">\(N_i\)</span> represents the total number of released animals at time <span class="math inline">\(i\)</span> and <span class="math inline">\(\underline{q} = f(\phi, p)\)</span> is a matrix which represents the cell probabilities depending on <span class="math inline">\(\boldsymbol{\phi}\)</span> and <span class="math inline">\(\boldsymbol{p}\)</span>.</p>
<p>Now we are going to explain how to construct <span class="math inline">\(\underline{q}\)</span>.</p>
<p>Firstly we need to explain how to compute the probability of a capture history. For example, if we have a capture history</p>
<p><span class="math display">\[
x_i = 1 \quad 1 \quad 0 \quad 1 \quad 1
\]</span></p>
<p>the probability of this capture history is</p>
<p><span class="math display">\[
\mathbb{P}(x_i) = \phi p \phi (1-p) \phi p \phi p
\]</span></p>
<p>So each cell in matrix <span class="math inline">\(\underline{q}\)</span> represent the probability of an individual being in the corresponding cell in the m-array. As the row sum of the probabilities is 1, the last column which represent the probability of never recaptured is 1 - row sum. For example, when <span class="math inline">\(T = 5\)</span>, matrix <span class="math inline">\(\underline{q}\)</span> has the form shown below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/q-marray.png" class="img-fluid figure-img"></p>
<figcaption>q matrix</figcaption>
</figure>
</div>
<p>We need the log likelihood function for simple calculation. The log likelihood function is constructed by</p>
<p><span class="math display">\[
l(\underline{x}, \theta) = \sum_{i}^{T-1} \log{Multinomial(N_i, \underline{q})} = \sum_{ i= 1}^{T-1} \sum_{j = 2}^{T}\text{m-array}[i, j] \times \log{\underline{q}[i, j]}.
\]</span></p>
<p>We create a function <code>caplik.constant</code> for the negative log likelihood function, then use <code>optim</code> to find the MLE of our parameters of interest, <span class="math inline">\(\boldsymbol{\theta}\)</span>. Transfer the estimate of <span class="math inline">\(\boldsymbol{\theta}\)</span> back to <span class="math inline">\(p\)</span> and <span class="math inline">\(\phi\)</span> using <code>plogis</code>. Also, we can obtain standard error for each parameter from inverting the Hessian matrix at the MLE.</p>
<p>We can compute the credible interval for each parameter using bootstrap method. Take 50 resamples, find lower and upper quantile for the estimated parameters. The MLE, SD, and 95% credible interval (CI) for estimated parameters are shown below.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">MLE</th>
<th style="text-align: left;">SD</th>
<th style="text-align: left;">CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(p\)</span></td>
<td style="text-align: left;">0.539</td>
<td style="text-align: left;">0.098</td>
<td style="text-align: left;">[0.473,0.592]</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\phi\)</span></td>
<td style="text-align: left;">0.932</td>
<td style="text-align: left;">0.093</td>
<td style="text-align: left;">[0.903,0.958]</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="sex-dependent-survival-probabilities" class="level2">
<h2 class="anchored" data-anchor-id="sex-dependent-survival-probabilities">2. Sex dependent survival probabilities</h2>
<p>Since the recapture probability is high (<span class="math inline">\(p =\)</span> 0.539), we do not expect any difference if we model them age or sex dependent. Hence, we would keep <span class="math inline">\(p\)</span> constant in this analysis. Now we are curious about whether the survival probabilities vary with sex. Let <span class="math inline">\(\phi_m\)</span> and <span class="math inline">\(\phi_f\)</span> to represent the survival probabilities of male and female. We split the database into 2 separated database according to their sex, and denote them <code>CH.m</code> and <code>CH.f</code> respectively.</p>
<p>The likelihood function is slightly different from the constant model, since we have to form two <span class="math inline">\(\underline{q}\)</span> matrix for both male and female. The log likelihood function becomes</p>
<p><span class="math display">\[
l(\underline{x};\theta) = l(\underline{x_m};\theta_m) + l(\underline{x_f};\theta_f)
\]</span></p>
<p>where</p>
<p><span class="math display">\[
l(\underline{x_m}, \theta_m) = \sum_{i = 1}^{T-1} \sum_{j = 2}^{T}\text{m-array}_m[i, j]\times \log{\underline{q_m}[i, j]} \quad \text{and}\\
l(\underline{x_f}, \theta_f) = \sum_{i = 1}^{T-1} \sum_{j = 2}^{T}\text{m-array}_f[i, j]\times \log{\underline{q_f}[i, j]},
\]</span></p>
<p>so we also need to construct <span class="math inline">\(\underline{q}\)</span> for the different sex class. Define function <code>caplik.sex</code> to compute the negative log likelihood for this model.</p>
<p>The estimates for <span class="math inline">\(p\)</span> and <span class="math inline">\(\phi\)</span> depends on sex are shown below.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">MLE</th>
<th style="text-align: left;">SD</th>
<th style="text-align: left;">CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(p\)</span></td>
<td style="text-align: left;">0.539</td>
<td style="text-align: left;">0.098</td>
<td style="text-align: left;">[0.476,0.583]</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\phi_m\)</span></td>
<td style="text-align: left;">0.92</td>
<td style="text-align: left;">0.135</td>
<td style="text-align: left;">[0.86,0.95]</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\phi_f\)</span></td>
<td style="text-align: left;">0.944</td>
<td style="text-align: left;">0.127</td>
<td style="text-align: left;">[0.885,0.977]</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The difference between <span class="math inline">\(\phi_m\)</span> and <span class="math inline">\(\phi_f\)</span> is about 0.02. From the result above, it seems like the sex of an individual does not affect the apparent survival probability.</p>
</section>
<section id="model-with-age-dependent-survival-probabilities" class="level2">
<h2 class="anchored" data-anchor-id="model-with-age-dependent-survival-probabilities">3. Model with Age-dependent survival probabilities</h2>
<p>Next, we want to see if the age of an individual affect the survival probabilities. Usually, young individuals have lower survival probabilities than adults. We denote <span class="math inline">\(\phi_a\)</span> as the apparent survival probability for individuals at age <span class="math inline">\(a\)</span>. We are going to consider different number of age classes:</p>
<ul>
<li><span class="math inline">\(a = 1, 2, 3+ //\phi_1, \phi_2, \phi_{3+}\)</span></li>
<li><span class="math inline">\(a = 1, 2, 3, 4+ //\phi_1, \phi_2, \phi_3, \phi_{4+}\)</span></li>
<li><span class="math inline">\(a = 1, 2, 3, 4, 5+ //\phi_1, \phi_2, \phi_3, \phi_4, \phi_{5+}\)</span></li>
</ul>
<p>then we decide which model is the best.</p>
<p>In CJS model, in m-array formulation, we will need to construct one m-array for each age class. For instance, for 3 age classes, we will have to construct 3 m-arrays and 3 <span class="math inline">\(\underline{q}\)</span> matrices accordingly.</p>
<p>Since the age of individuals changes through years, cell probabilities in <span class="math inline">\(\underline{q}\)</span> are different from the sex case. The probability of capture history also changes as we have a different <span class="math inline">\(\phi_a\)</span> for different age <span class="math inline">\(a\)</span>.</p>
<p>Using the same example as before, for a capture history</p>
<p><span class="math display">\[
x_i = 1 \quad 1 \quad 0 \quad 1 \quad 1
\]</span></p>
<p>the probability of this capture history is now</p>
<p><span class="math display">\[
\mathbb{P}(x_i) = \phi_1p\phi_2(1-p)\phi_3p\phi_3p
\]</span></p>
<p>While we have only 3 age classes, <span class="math inline">\(\phi_a\)</span> beyond the third occasion after the first capture are all <span class="math inline">\(\phi_3\)</span> instead of <span class="math inline">\(\phi_4, \phi_5\)</span> etc.</p>
<p>Now, for example, when <span class="math inline">\(T = 5\)</span> and if we choose to have 3 age classes, the <span class="math inline">\(\underline{q}\)</span> for age 1 individuals is like</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/q-marray-age.png" class="img-fluid figure-img"></p>
<figcaption>q matrix for age 1 individuals (total 3 age classes)</figcaption>
</figure>
</div>
<p>Similar structure will have ages 2, 3, 4 and 5+. For the likelihood function, the construction is the same as before with log likelihood</p>
<p><span class="math display">\[
l(\underline{x};\theta) = \sum_{a}^{A} l(\underline{x_{a}};\theta_{a})
\]</span> with <span class="math inline">\(A = 3, 4, 5\)</span> representing the number of age class. For example, <span class="math inline">\(a = 1, 2, 3, 4\)</span> for <span class="math inline">\(A = 4\)</span>.</p>
<p>For our data, we do not have any individuals re-captured on the occasion after the first capture, i.e.&nbsp;we have not seen any 1 year old individual (which is often the case), so we can not estimate <span class="math inline">\(\phi_1\)</span> and <span class="math inline">\(p\)</span> separately, only its product <span class="math inline">\(\phi_1 p\)</span>. Therefore we let <span class="math inline">\(\phi_1 = 1\)</span> and <span class="math inline">\(p_1 = 0\)</span> (here <span class="math inline">\(p_1\)</span> means <span class="math inline">\(p\)</span> for occasion 2), the rest of the calculation remains the same. Therefore, <span class="math inline">\(\phi_2\)</span> can be interpreted as the survival probability until 2 year old. Define functions <code>caplik.age3</code>, <code>caplik.age4</code> and <code>caplik.age5</code> for the three models.</p>
<p>The estimate for each model is shown below.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 5%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 5%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 5%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">3 age classes</th>
<th style="text-align: left;"></th>
<th style="text-align: left;"></th>
<th style="text-align: left;">4 age classes</th>
<th style="text-align: left;"></th>
<th style="text-align: left;"></th>
<th style="text-align: left;">5 age classes</th>
<th style="text-align: left;"></th>
<th style="text-align: left;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">MLE</td>
<td style="text-align: left;">SD</td>
<td style="text-align: left;">CI</td>
<td style="text-align: left;">MLE</td>
<td style="text-align: left;">SD</td>
<td style="text-align: left;">CI</td>
<td style="text-align: left;">MLE</td>
<td style="text-align: left;">SD</td>
<td style="text-align: left;">CI</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(p\)</span></td>
<td style="text-align: left;">0.705</td>
<td style="text-align: left;">0.107</td>
<td style="text-align: left;">[0.651,0.768]</td>
<td style="text-align: left;">0.752</td>
<td style="text-align: left;">0.107</td>
<td style="text-align: left;">[0.686,0.801]</td>
<td style="text-align: left;">0.71</td>
<td style="text-align: left;">0.107</td>
<td style="text-align: left;">[0.643,0.803]</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\phi_2\)</span></td>
<td style="text-align: left;">0.636</td>
<td style="text-align: left;">0.235</td>
<td style="text-align: left;">[0.556,0.742]</td>
<td style="text-align: left;">0.592</td>
<td style="text-align: left;">0.235</td>
<td style="text-align: left;">[0.507,0.67]</td>
<td style="text-align: left;">0.605</td>
<td style="text-align: left;">0.235</td>
<td style="text-align: left;">[0.484,0.677]</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\phi_3\)</span></td>
<td style="text-align: left;">0.981</td>
<td style="text-align: left;">0.114</td>
<td style="text-align: left;">[0.965,0.992]</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">0.252</td>
<td style="text-align: left;">[1,1]</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">0.252</td>
<td style="text-align: left;">[0.998,1]</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\phi_4\)</span></td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">0.967</td>
<td style="text-align: left;">0.129</td>
<td style="text-align: left;">[0.951,0.992]</td>
<td style="text-align: left;">0.979</td>
<td style="text-align: left;">0.293</td>
<td style="text-align: left;">[0.926,1]</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\phi_5\)</span></td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">0.143</td>
<td style="text-align: left;">[0.941,1]</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>From the results we can see that individuals with more than 2 years old have a higher apparent survival probability for all models as we expected.</p>
<p>We have done three age-dependent models, now we are going to decide which one is the best model. In this analysis, we are going to use the Akaike Information Criterion (AIC) approach for model-selection. The AIC of a model is defined as</p>
<p><span class="math display">\[
AIC = -2\log{L(\underline{x}, \hat{\theta})} + 2d
\]</span> where <span class="math inline">\(d\)</span> is the number of parameters estimated. The model with the smallest AIC value is preferred.</p>
<p>Compute the AIC for each model, the result is shown below</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">3 age classes</td>
<td style="text-align: right;">635.002</td>
</tr>
<tr class="even">
<td style="text-align: left;">4 age classes</td>
<td style="text-align: right;">637.002</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5 age classes</td>
<td style="text-align: right;">639.002</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The model with 3 age classes has the lowest AIC = 635.002 and therefore it is the best among the three age-dependent models.</p>
</section>
<section id="models-with-survival-probabilities-age-and-sex-dependent" class="level2">
<h2 class="anchored" data-anchor-id="models-with-survival-probabilities-age-and-sex-dependent">4. Models with survival probabilities age and sex dependent</h2>
<p>We have already implicated models where survival probabilities were sex-dependent as well as age-dependent. Now we are going to combine them together, which means that survival probabilities we will depend on age and sex, <span class="math inline">\(\phi_{a,s}\)</span>. For example, <span class="math inline">\(\phi_{1,m}\)</span> represent survival probability for individuals who are male and at age 1. For 3 age classes, we have in total 7 parameters, a constant <span class="math inline">\(p\)</span>, and 6 <span class="math inline">\(\phi\)</span> for both males and females at different age. We will also do 3 models with different numbers of age classes as before.</p>
<p>The log likelihood function now becomes</p>
<p><span class="math display">\[
l(\underline{x};\theta) = \sum_{a}^{A} l(\underline{x_{a,m}};\theta_{a,m}) + \sum_{a}^{A} l(\underline{x_{a,f}};\theta_{a,f})\\
\]</span></p>
<p>We use the same approach as before, define three functions <code>caplik.age3.sex</code>, <code>caplik.age4.sex</code> and <code>caplik.age5.sex</code> accordingly, the result for each model shows below.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 11%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 11%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">3 age class</th>
<th style="text-align: left;"></th>
<th style="text-align: left;"></th>
<th style="text-align: left;"></th>
<th style="text-align: left;">4 age class</th>
<th style="text-align: left;"></th>
<th style="text-align: left;"></th>
<th style="text-align: left;"></th>
<th style="text-align: left;">5 age class</th>
<th style="text-align: left;"></th>
<th style="text-align: left;"></th>
<th style="text-align: left;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">sex</td>
<td style="text-align: left;">male</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">female</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">male</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">female</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">male</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">female</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">MLE</td>
<td style="text-align: left;">SD</td>
<td style="text-align: left;">MLE</td>
<td style="text-align: left;">SD</td>
<td style="text-align: left;">MLE</td>
<td style="text-align: left;">SD</td>
<td style="text-align: left;">MLE</td>
<td style="text-align: left;">SD</td>
<td style="text-align: left;">MLE</td>
<td style="text-align: left;">SD</td>
<td style="text-align: left;">MLE</td>
<td style="text-align: left;">SD</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(p\)</span></td>
<td style="text-align: left;">0.705</td>
<td style="text-align: left;">0.107</td>
<td style="text-align: left;">0.705</td>
<td style="text-align: left;">0.107</td>
<td style="text-align: left;">0.691</td>
<td style="text-align: left;">0.107</td>
<td style="text-align: left;">0.691</td>
<td style="text-align: left;">0.107</td>
<td style="text-align: left;">0.745</td>
<td style="text-align: left;">0.107</td>
<td style="text-align: left;">0.745</td>
<td style="text-align: left;">0.107</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\phi_2\)</span></td>
<td style="text-align: left;">0.621</td>
<td style="text-align: left;">0.327</td>
<td style="text-align: left;">0.653</td>
<td style="text-align: left;">0.334</td>
<td style="text-align: left;">0.632</td>
<td style="text-align: left;">0.327</td>
<td style="text-align: left;">0.664</td>
<td style="text-align: left;">0.334</td>
<td style="text-align: left;">0.593</td>
<td style="text-align: left;">0.327</td>
<td style="text-align: left;">0.625</td>
<td style="text-align: left;">0.334</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\phi_3\)</span></td>
<td style="text-align: left;">0.981</td>
<td style="text-align: left;">0.171</td>
<td style="text-align: left;">0.981</td>
<td style="text-align: left;">0.153</td>
<td style="text-align: left;">0.981</td>
<td style="text-align: left;">0.348</td>
<td style="text-align: left;">0.999</td>
<td style="text-align: left;">0.364</td>
<td style="text-align: left;">0.997</td>
<td style="text-align: left;">0.348</td>
<td style="text-align: left;">0.998</td>
<td style="text-align: left;">0.364</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\phi_4\)</span></td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">0.197</td>
<td style="text-align: left;">0.99</td>
<td style="text-align: left;">0.169</td>
<td style="text-align: left;">0.999</td>
<td style="text-align: left;">0.416</td>
<td style="text-align: left;">0.967</td>
<td style="text-align: left;">0.413</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\phi_5\)</span></td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">0.957</td>
<td style="text-align: left;">0.224</td>
<td style="text-align: left;">0.975</td>
<td style="text-align: left;">0.186</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Compute the AIC for each model.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">3 age classes</td>
<td style="text-align: right;">639.195</td>
</tr>
<tr class="even">
<td style="text-align: left;">4 age classes</td>
<td style="text-align: right;">648.023</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5 age classes</td>
<td style="text-align: right;">624.962</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>From the results above, the model with the lowest AIC = 624.962 is the one with 5 age classes. As we can see, there is almost no sex effect on the estimate of survival probabilities in this model. Hence we would like to set some of the <span class="math inline">\(\phi.m\)</span> and <span class="math inline">\(\phi.f\)</span> to be the same for some certain age class to see if the model improves.</p>
</section>
<section id="model-selection" class="level2">
<h2 class="anchored" data-anchor-id="model-selection">Model selection</h2>
<p>Now we choose 5 models, and assess their performance:</p>
<ul>
<li>Model 1: all survival probabilities differ for males and females</li>
<li>Model 2: <span class="math inline">\(\phi_{2.m} = \phi_{2.f}\)</span></li>
<li>Model 3: <span class="math inline">\(\phi_{2, 3.m} = \phi_{2, 3.f}\)</span></li>
<li>Model 4: <span class="math inline">\(\phi_{2, 3, 4.m} = \phi_{2, 3, 4.f}\)</span></li>
<li>Model 5: constant survival probabilities for both males and females</li>
</ul>
<p>Following the same methedology previously explained, we form the likelihood function for each model and then use <code>optim</code> to find the MLE. We then compute the AIC of each model with the following results,</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: left;">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1. all phi depends on sex</td>
<td style="text-align: left;">624.544</td>
</tr>
<tr class="even">
<td style="text-align: left;">2. phi2.m = phi2.f</td>
<td style="text-align: left;">719.15</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3. phi2,3.m = phi2,3.f</td>
<td style="text-align: left;">625.901</td>
</tr>
<tr class="even">
<td style="text-align: left;">4. phi2,3,4.m = phi2,3,4.f</td>
<td style="text-align: left;">619.17</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5. constant phi</td>
<td style="text-align: left;">628.78</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Model 4 gives the lowest AIC = 619.17. So we set <span class="math inline">\(\phi_{2, 3, 4.m} = \phi_{2, 3, 4.f}\)</span>, and a different survival probabilities for 5 years old males and females, the estimate of the parameters are shown below.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">MLE</th>
<th style="text-align: left;">SD</th>
<th style="text-align: left;">CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(p\)</span></td>
<td style="text-align: left;">0.753</td>
<td style="text-align: left;">0.107</td>
<td style="text-align: left;">[0.665,0.783]</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\phi_2\)</span></td>
<td style="text-align: left;">0.591</td>
<td style="text-align: left;">0.235</td>
<td style="text-align: left;">[0.49,0.685]</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\phi_3\)</span></td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">0.252</td>
<td style="text-align: left;">[0.963,1]</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\phi_4\)</span></td>
<td style="text-align: left;">0.984</td>
<td style="text-align: left;">0.293</td>
<td style="text-align: left;">[0.923,1]</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(\phi_{5,m}\)</span></td>
<td style="text-align: left;">0.952</td>
<td style="text-align: left;">0.224</td>
<td style="text-align: left;">[0.916,1]</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(\phi_{5,f}\)</span></td>
<td style="text-align: left;">0.971</td>
<td style="text-align: left;">0.186</td>
<td style="text-align: left;">[0.923,1]</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p>In conclusion, we have implement CJS models to estimate the apparent survival probability and recapture probability. We have built several different models which regard to age and/or sex of the individuals, and we have used AIC method for model selection. The best model (in terms of AIC) was that with constant recapture probability, common sex-survival probabilities for ages 2 to 4, and different sex-survival probabilities for age 5+.</p>
<p>Guillemot are long live sea birds that in some cases they can live about 40 years. Although both sexes take care of the chick, the energy spent in breeding differs between sexes. This fact may affect the survival probabilities, mainly at older ages. The results are in line with this, showing a common survival probabilities for both sexes until 4 years old (juvenile birds) and being slightly different for breeders (5+).</p>
<p>However, we can see that the difference in the survival probability for males and females are very small. Also, we have higher <span class="math inline">\(\phi_3\)</span> and <span class="math inline">\(\phi_4\)</span> than <span class="math inline">\(\phi_5\)</span>. This may not be the case for the whole population. Further analyses are needed to see if there are other factors affecting there results.</p>
<p>In this project we only discuss the effects of sex and age on survival probabilities, but there are many other associated factors that can affect the survival probabilities, which are also worth investigating. In addition, due to the long life expectancy, more age classes can be added to see how survival probabilities differ by age.</p>
<p>Finally, it is worth to note that the estimated parameters are higher than the expected. This may be because of how the data is collected. For our special case, this lab has a globally unique research platform with an artificial rock shelf with enough space to host hundreds of breeding birds. The base of this platform rests in the middle of an established Common Guillemot colony, so instead of staring with binoculars or telescope in thousand meters away, scientists can study the birds from a distance of bare centimeters. This makes sure the data has high precision (recapture probability is almost 1).</p>
<p>This report only shows the result of this database, which does not represent the estimation for the entire population.</p>
</section>
<section id="reference" class="level2">
<h2 class="anchored" data-anchor-id="reference">Reference</h2>
<p>Seber, G. A. F. and Schofield, M. R. (2019). Capture-Recapture: Parameter Estimation for Open Animal Populations. Springer.</p>
<p>King, R. (2014). Statistical Ecology. The Annual Review of Statistics and Its Application, 1:401–426.</p>
<p>McCrea, R. and Morgan, B. J. T. (2015). Analysis of Capture-recapture Data. CRC Press.</p>
<p>Balticseabird.com. (2022). Stora Karlsö Auk Lab – BSP. [online] Available at: <a href="http://www.balticseabird.com/auk-lab/" class="uri">http://www.balticseabird.com/auk-lab/</a> [Accessed 29 August 2022].</p>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Ashlynn Lu 2024</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/AshlynnLu/profile-page/edit/main/posts/2022-08-19_guillemot-survival/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/AshlynnLu/profile-page/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/AshlynnLu">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/kexin-lu-246256228">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.facebook.com/kexin.lu.370">
      <i class="bi bi-facebook" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>